---
name: test-cross-gem
on:
  push:
    paths:
      - "cross-gem/**/*"
      - ".github/workflows/test-cross-gem.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  SCCACHE_LOG: debug
jobs:
  test:
    name: Testing ${{ matrix.repo.slug }} on ${{ matrix.ruby-platform }}
    strategy:
      fail-fast: false
      matrix:
        repo:
          - name: "oxidize-rb/oxi-test"
            slug: oxi-test
            ref: main
            ruby-versions: "3.0, 3.1, 3.2, 3.3"
        ruby-platform:
          - "x86_64-linux"
          - "arm64-darwin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.ref }}

      - uses: actions/checkout@v4
        with:
          path: ./tmp/actions

      - uses:  ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bunder-cache: true

      - uses: ./tmp/actions/cross-gem
        id: cross-gem
        with:
          ruby-versions: ${{ matrix.repo.ruby-versions }}
          platform: ${{ matrix.ruby-platform }}

      - name: Run tests
        run: |
          : Run tests

          if ! $(find pkg -name "oxi-test-*-${{ matrix.ruby-platform }}.gem" | wc -l | grep -q 1); then
            echo "Gem not found in pkg/ directory"
            echo "Found:"
            ls -l pkg
            exit 1
          fi
